CFLAGS=-Wall
CFLAGS+=-g
CFLAGS+=-I../json-c/include/json-c

info: info.o ../json-c/lib/libjson-c.a

json_test1: json_test1.o  ../json-c/lib/libjson-c.a

json_test4: json_test4.o ../json-c/lib/libjson-c.a

json_test_cast: json_test_cast.o ../json-c/lib/libjson-c.a