#!/bin/bash

echo "
#include <stdio.h>
int main(void)
{"
echo -e "printf(\"\\"

while IFS='' read -r line; do
	echo -n "$line" | sed -e 's/\\/\\&/g' -e 's/"/\\&/g'
	echo "\\n\\"
done < "$1"

echo "\");
return 0;
}"
